apiVersion: storage.spotahome.com/v1alpha2
kind: RedisFailover
metadata:
  name: redisfailover-pmem
spec:
  sentinel:
    replicas: 3
    customConfig:
      - "protected-mode no"
  redis:
    replicas: 3
    customConfig:
      - "protected-mode no"
      - "pmdir /data 100Mi"
    image: hub.docker.intel.com/redis_pmem/redis
    version: latest
    storage:
      persistentVolumeClaim:
        metadata:
          name: redisfailover-pmem-data
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 100Mi
          storageClassName: pmem-csi-sc
